### ISSUE TITLE
Delete old client

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.client#103]
Jad recently commented that he has no intention to maintain old client. I saw no changes to the client in 4.0.0 and I am not planning to maintain it either. Existing users are expected to stay on v2.x for the time being.

I suggest to remove it and not include it in the 4.0.0 release. I will remove it this week unless there are good arguments to keep it.

**Comment by jamsden** [comment]
Maybe deprecate?

**Comment by berezovskyi** [comment]
I am OK with it (if you mean to deprecate every single class in it). But unless we remove it now, the "deprecated" client will be released with 4.0.0 version. What's the point?

**Comment by jamsden** [comment]
If its deprecated, users can upgrade to 4.0 without having a client API breaking change. That will give them time to adapt.

**Comment by berezovskyi** [comment]
Ok, let's do that then and target for removal in 5.0
