### ISSUE TITLE
Please update OSLCClient to use apache http 4.5.x methods

### ISSUE THREAD

**Issue by lewistsao** [eclipse/lyo.client#11]
This is an ehancement request.
From sample pom.xml file, it appears lyo.client is using apache http 4.5.x.
However the code still uses defaulthttpclient which has been deprecated since 4.3.
On top of that, there are various deficiencies that need to be fixed - it does not handle the javax.net.ssl.keystore.*, proxy, javax.net.ssl.truststore.* system properties among others.
This would help poeple like me who are occasional users of lyo.client oslc tremendously.
Many thanks

**Comment by berezovskyi** [comment]
Hello! I totally agree, this is something that definitely needs to be done. Unfortunately I have a lot of other things to do. BTW, did I mention we welcome pull requests? 😊

Having said that, @jadelkhoury just submitted a patch that begins the migration from Apache Wink client to a standard JAX-RS 2.0 client spec: https://github.com/eclipse/lyo.client/pull/10 He will certainly welcome your knowledge and help!

**Comment by berezovskyi** [comment]
And yes, welcome to Github, @lewistsao! 🎉

**Comment by berezovskyi** [comment]
Just did an initial PR review on Jad's code. If you are ready to help, just leave a comment under #10 and I am sure Jad will be glad if you start pushing commits.

**Comment by jadelkhoury** [comment]
you beat me to it @berezovskyi 
@lewistsao we are aiming to upgrade the whole of Lyo (including Client) to move from Wink (JAX-RS 1.0) to JAX-RS 2.0. This will certainly also imply an update to the Apache Http library.

The patch https://github.com/eclipse/lyo.client/pull/10 does already use httpClient 4.5.2. 
But, as it is, I have not managed to make use of this Apache Client, since I am not too familar with it in this context. See my comments on https://github.com/eclipse/lyo.client/pull/10#issuecomment-434983609

So, if you have any input on that part, it would be great.

**Comment by lewistsao** [comment]
Hi all,

Unfortunately I'm not a real Java developer and the whole http stack is well beyond my ability.

I have only been able to modify the call from 'defaulthttpclient' to 'systemdefaulthttpclient' to satisfy my immediate need. The causes a compile error, re http threads, which I commented out. But the 'system...' call is also deprecated.

I had a look at using CloseableHttpClient but decided too much code needs changing and way beyond my ability.

Apologies for asking for things but not making any contribution.

⁣Sent from BlueMail ​

**Comment by berezovskyi** [comment]
Well, you are editing Java code... now you are a Java developer, @lewistsao! ;)

No worries, we will keep it in our mind. Thanks for pointing us in the direction of the CloseableHttpClient. For my future self: https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html

@lewistsao if you don't mind me asking, which OSLC-enabled systems are you querying with the help of Lyo? It's just such a niche area I feel obliged to ask! Maybe https://gitter.im/eclipse/lyo is a better place to continue the discussion.

**Comment by jadelkhoury** [comment]
@lewistsao ideas and suggestions for improvements are very welcome. That’s what drives the community forward. 
Keep an eye on the #10 patch to see when your needed changes are integrated into our SDK

**Comment by jadelkhoury** [comment]
@berezovskyi is there a way in github to state that this issue “depends on” #10 ?

**Comment by jamsden** [comment]
The old oslc-java-client uses httpclient 4.5.2 while the new oslc4j-client uses 4.5.6 So closing.
