### ISSUE TITLE
oslc4j-json4j-provider still depends on wink-json4j

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo.client#30]
On branch F_ajx-rs-2.0-post2.4.0 which should have all Wink dependencies removed.

**Comment by berezovskyi** [comment]
No need for that. There is nothing JAX-RS related there.

**Comment by berezovskyi** [comment]
Unless you want to switch to something well-maintained.

**Comment by berezovskyi** [comment]
i.e. you can use this particular artifact with Jersey.

**Comment by jamsden** [comment]
So this doesn't pull in a lot of Wink into the oslc4j-client apps? If not, this can be closed.

**Comment by berezovskyi** [comment]
I will check and get back to you

**Comment by berezovskyi** [comment]
Depends only on JUnit.

**Comment by berezovskyi** [comment]
https://github.com/apache/attic-wink/blob/trunk/wink-json4j/pom.xml#L29
