### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.client#31]
![image](https://user-images.githubusercontent.com/64734/52152636-5b864280-2677-11e9-924d-339769b00368.png)

**Comment by berezovskyi** [comment]
https://travis-ci.org/eclipse/lyo.client/jobs/493959502#L1978: `JEEFormAuthenticator.java:[115,47] cannot find symbol`

**Comment by jadelkhoury** [comment]
I tried to get the new oslc4j-Client from our snapshots maven repo and it is not there at all. 

I assume this issue highlight the same problem. 
So I assume one has to build from source for now?

**Comment by berezovskyi** [comment]
See #40

--
/Andrew

18 mars 2019 kl. 08:58 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


I tried to get the new oslc4j-Client from our snapshots maven repo and it is not there at all.

I assume this issue highlight the same problem.
So I assume one has to build from source for now?

**Comment by jamsden** [comment]
oslc4j-client is getting the wrong version of JAX-RS. It should be jax.ws.rs-api : 2.1.1. I think this is being picked up from oslc4j-core which is probably using jsr311-api.

**Comment by jadelkhoury** [comment]
> oslc4j-client is getting the wrong version of JAX-RS. It should be javax.ws.rs-api : 2.1.1. I think this is being picked up from oslc4j-core which is probably using jsr311-api.

Looking at the "effective POM" for oslc4j-client, and I can clearly see the following. plus no trace of any jsr311-api. Are you sure?
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
      <version>2.1.1</version>
      <scope>compile</scope>
    </dependency>

**Comment by jamsden** [comment]
No, but that's what it looks like from the compilation errors in the build.

**Comment by berezovskyi** [comment]
fixed since
