### ISSUE TITLE
Update / Submit CQs as needed for JAX-RS 2.0 changes to core and client

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo.client#33]

**Comment by berezovskyi** [comment]
To help out a bit, I need a list of the CQs that have to be submitted.

**Comment by jamsden** [comment]
Probably crazy, but is there a tool that parses pom files and detects missing CQs for the dependencies?

**Comment by jamsden** [comment]
Otherwise its probably easy enough to manually search for each dependency version and make sure its got an approved CQ.

**Comment by jamsden** [comment]
mvn dependency:tree -- is it sufficient to only check the root elements in this tree assuming that if those have proper CQs then all their dependencies do too?

oslc4j-client:
- [ ] org.mockito:mockito-core:jar:2.23.4:test - 2.23.0

**Comment by berezovskyi** [comment]
Yes, should be. And I don't think we need to CQ test deps.

--
/Andrew

6 feb. 2019 kl. 02:04 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


mvn dependency:tree -- is it sufficient to only check the root elements in this tree assuming that if those have proper CQs then all their dependencies do too?

oslc4j-client:

  *    org.mockito:mockito-core:jar:2.23.4:test - 2.23.0

**Comment by jamsden** [comment]
There have been no changes to the dependencies in oslc-java-client since 2.4.0, so there are no pending CQs there either.
