### ISSUE TITLE
OSLC queries were being executed with no query parameters

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.client#34]
From @jamsden:

> In OslcQuery.applyQueryParams and applyPagination, WebTarget.queryPath returns a new instance of WebTarget, it doesn't add the query parameter to the target WebTarget. So all OSLC queries were being executed with no query parameters.

**Comment by jamsden** [comment]
This was not broken in the old oslc-java-client. And it is now fixed in oslc4j-client. So this can be closed.
