### ISSUE TITLE
issues in the new client

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.client#40]
Major portion of wink-based client is duplicated in the new client. I don't have time or energy to port/backport fixes like #5 to both clients. Thus, I would just leave the old client at 2.4.0 without further maintenance unless someone steps up to make 2.4.x releases.

Furthermore, duplicating resource classes makes it hard/impossible to develop proper libraries. I have raised this issue with @jadelkhoury regarding the code that is generated by LyoD (equally hard to write portable helpers) and Jad suggested to switch to something like https://github.com/eclipse/lyo.domains/

**Comment by berezovskyi** [comment]
Also, the new client is not in the Maven repo yet.

**Comment by berezovskyi** [comment]
also, sample code is referring to Lyo 2.3: https://travis-ci.org/eclipse/lyo.client/jobs/494093025#L2678

**Comment by berezovskyi** [comment]
@jadelkhoury yes, I recorded this here.

**Comment by berezovskyi** [comment]
even worse:

- exceptions are duplicated
- new client shall not use "custom" POJOs but instead use `lyo.domains` classes

**Comment by jamsden** [comment]
I'm trying to find some time to work in the client.

**Comment by berezovskyi** [comment]
old client is part of the release but not getting any fixes
