### ISSUE TITLE
Help  Requested POM file

### ISSUE THREAD

**Issue by ukrishne** [eclipse/lyo.client#41]
Hello OSLC experts, 

I am beginer to OSLC, am trying to run the java file "lyo.client/oslc4j-client-samples/src/main/java/org/eclipse/lyo/client/oslc/samples/RMSample.java" in eclipse but in POM file **i am getting below error**

"Failure to transfer org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until
the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://
repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target"

**when i tried "POM->Run as ->Moven Clean" i am getting below error message** "[INFO] Scanning for projects...
[INFO]
[INFO] -------< org.eclipse.lyo.samples.clients:oslc4j-client-samples >--------
[INFO] Building org.eclipse.lyo.samples.clients 2.3.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.117 s
[INFO] Finished at: 2019-03-18T11:12:32+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException'
can you please help me to resolve this error

There is no proxy 

thanks in Advance

**Comment by berezovskyi** [comment]
Hi,

From https://stackoverflow.com/questions/25911623/problems-using-maven-and-ssl-behind-proxy you are either:

- Using old Ubuntu
- Using old Maven
- Using old patch release of JDK8

Please check and upgrade if needed. Disregard the proxy part.

--
/Andrew

18 mars 2019 kl. 07:46 skrev ukrishne <notifications@github.com<mailto:notifications@github.com>>:


Hello OSLC experts,

I am beginer to OSLC, am trying to run the java file "lyo.client/oslc4j-client-samples/src/main/java/org/eclipse/lyo/client/oslc/samples/RMSample.java" in eclipse but in POM file i am getting below error

"Failure to transfer org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until
the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://
repo.maven.apache.org/maven2<http://repo.maven.apache.org/maven2>): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target"

when i tried "POM->Run as ->Moven Clean" i am getting below error message "[INFO] Scanning for projects...
[INFO]
[INFO] -------< org.eclipse.lyo.samples.clients:oslc4j-client-samples >--------
[INFO] Building org.eclipse.lyo.samples.clients 2.3.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.117 s
[INFO] Finished at: 2019-03-18T11:12:32+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException'
can you please help me to resolve this error

There is no proxy

thanks in Advance

**Comment by ukrishne** [comment]
HI Andrew, 

Thank you so much, can you please give me step by step instarcutctions to execute the samples.
i tried "https://wiki.eclipse.org/Lyo/BuildClient" looks like it is old.

and also i considering "https://github.com/ld4mbse/oslc4j"  this as reference, please let me know if you have  better link.

thanks in Advance

**Comment by berezovskyi** [comment]
As written under https://github.com/eclipse/lyo.client/blob/master/README.md#repository-structure, the sample code is now located under https://github.com/OSLC/lyo-samples/tree/master/lyo-client-samples.

Also, you are trying to run the sample code for the v4 version of the library that has not been released yet.

**Comment by jadelkhoury** [comment]
> As written under https://github.com/eclipse/lyo.client/blob/master/README.md#repository-structure, the sample code is now located under https://github.com/OSLC/lyo-samples/tree/master/lyo-client-samples.

Why does this repository still has the sample folders such as oslc-java-samples then? should we not delete them, if they are moved?

**Comment by berezovskyi** [comment]
We should

--
–Andrew.

2019-03-19  kl. 21:26 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


As written under https://github.com/eclipse/lyo.client/blob/master/README.md#repository-structure, the sample code is now located under https://github.com/OSLC/lyo-samples/tree/master/lyo-client-samples.

Why does this repository still has the sample folders such as oslc-java-samples then? should we not delete them, if they are moved?
