### ISSUE TITLE
Bundling the client as osgi bundle

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.client#6]
Similar to Lyo.core (as defined in Bundling oslc4j as osgi bundle), it would be great if we can also  build the client as a bundle. 

Actual usage scenario, an EMF/eclipse application needs to consume OSLC resources from an OSLC server. We need to be able to include the client code as a plugin

**Comment by berezovskyi** [comment]
Nice! Can you try making an initial manifest for the bundle, please? Ie which packages to export etc.

**Comment by jadelkhoury** [comment]
The only project worth exporting seems to be "org.eclipse.lyo.client.java"

**Comment by berezovskyi** [comment]
The resolution from the call with Sebastien is that we try splitting the build into two phases, build a Core/Client bundle first with Apache BND, manually create a P2 repo for it and only then run the Tycho build with a dependency being resolved through the newly made P2 site.

**Comment by berezovskyi** [comment]
Resolved by https://github.com/eclipse/lyo.designer/pull/172
