### ISSUE TITLE
OSLC Client: can you provide a method createResource where custom headers can be provided?

### ISSUE THREAD

**Issue by rsjazz** [eclipse/lyo.client#8]
Hi,

I am using OSLC4J and have found that there are a lot of APIs that are not completely OSLC. Especially Doors Next often requires additional headers. I had to create a subclass of org.eclipse.lyo.client.oslc.OslcClient to add a new method

public ClientResponse createResource(String url, final Object artifact, Map<String, String> requestHeaders, 
String mediaType, String acceptType)

to add custom headers. This requires also creating a new RootServicesHelper delegating to the JazzRootServicesHelper in order to get a custom form auth client for which I had to copy the code from org.eclipse.lyo.client.oslc.jazz.JazzFormAuthClient.

This works, but is brittle and makes maintenance a bit harder, just to get the custom header in.

All the HTTP methods should allow additional headers, if possible.

Thanks, Ralph

**Comment by berezovskyi** [comment]
Hello Ralph, I completely understand your need for an extra method. If you can make a pull request, I will be glad to review it and merge it. We are planning Lyo 2.4.0 release for Nov 7 and we might get it in before the public review begins (next Wed).

P.S. @jamsden you are working with the Client more than me, does it make sense to you?

**Comment by rsjazz** [comment]
@jamsden provided me with a valuable hint. It appears to be possible to use an HTTPRequestInterceptor to provide default headers and even to remove header information.

		HashMap<String, String> header = new HashMap<String, String>();
		header.put("Configuration-Context", target.getAbout().toString());
		
		HttpRequestInterceptor requestHeaderFixer = new CustomHttpRequestInterceptor(header);
		((DefaultHttpClient)client.getHttpClient()).addRequestInterceptor(requestHeaderFixer);

Instantiates an interceptor. In that interceptor the new headers are provided. Or even overwritten. E.g. 


public class CustomHttpRequestInterceptor implements HttpRequestInterceptor {

	HashMap<String, String> requestHeaders = null;
	
	public CustomHttpRequestInterceptor(HashMap<String, String> headers) {
		requestHeaders=headers;
	}

	@Override
	public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
		boolean acceptSet = false;
		boolean versionSet = false;
		boolean mediaTypeSet = false;

		// Add in any request headers.
		request.removeHeaders("Sample");
		if (requestHeaders != null) {
			for (Map.Entry<String, String> entry : requestHeaders.entrySet()) {
				// Add the header.
				request.addHeader(entry.getKey(),entry.getValue());

				// Remember if we've already set Accept or
				// OSLC-Core-Version.
				if ("accept".equalsIgnoreCase(entry.getKey())) {
					acceptSet = true;
				}
				if (("content-type").equalsIgnoreCase(entry.getKey())) {
					mediaTypeSet = true;
				}

				if ("OSLC-Core-Version".equalsIgnoreCase(entry.getKey())
						|| "DoorsRP-Request-Type"
								.equalsIgnoreCase(entry.getKey())) {
					versionSet = true;
				}
			}
		}

		if (!acceptSet) {
			request.addHeader("Accept","application/rdf+xml");
		}

		if (!versionSet) {
			request.addHeader("application/rdf+xml", "2.0");
		}

		if (!mediaTypeSet) {
			request.addHeader("content-type","application/rdf+xml");
		}				
	}			
}

**Comment by rsjazz** [comment]
The request is not really needed. Thanks! @jamsden
