### ISSUE TITLE
Attribute Value URI can't be resolved

### ISSUE THREAD

**Issue by Kira-Cesonia** [eclipse/lyo.client#93]
While reading out a requirement using:
```
		ClientResponse requirementResponse = oslcOauthClient
			.getResource(requirementURL, OslcMediaType.APPLICATION_RDF_XML);
		Requirement requirement = requirementResponse.getEntity(Requirement.class);
```

...I get a requirement object that among many more easily parseable attributes also has some with URIs, such as this one (in contrast to an easier parseable value):

```
requirement
└extendedProperites
 ├[7]
 │├QName key = {http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/}attrDef-1003
 │└XMLLiteral value = <div>This is the Additional Info Value</div>
 └[8]
  ├QName key = {http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/}attrDef-1025
  └URI value = http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1
```

The main question is: How do I resolve the URI that is returned here (http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1) into an actual value?

Intuitively, I tried `oslcOauthClient.getResource(http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1, OslcMediaType.APPLICATION_RDF_XML);`. However, that just returned the Formal Module in its XML Form.

Or simply put, these two requests return effectively the same response:

* `oslcOauthClient.getResource(http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100)`
* `oslcOauthClient.getResource(http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1)`

By pasting these URLs into a browser, I was able to confirm that this appears to be a redirection issue in DWA, where http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1 for some reason is automatically redirected to http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100 .

So, what can I do about this? All that I know is that I have the URI http://localhost:8080/dwa/rm/urn:rational::1-5efc6f9a4ff877cf-M-00000100/types/attrDef-1025#1, and I want to know the value it contains. But for some reason that value is not accessible. 

Am I using the wrong function in LYO? Or is does the problem lie somewhere else?

**Comment by jadelkhoury** [comment]
Hi

Since this does not seem to be a bug or a request for a change, I recommend you share your queries on our forum https://forum.open-services.net/ or email the Lyo-Dev mailing list lyo-dev@eclipse.org. You then have a better chance of reaching more people that may be able to help there.

I don't have a direct answer that can directly solve your answer, but I may be able to share some tips. But to avoid duplicating myself, I'd rather share it on the forum/mail, so that others can hopefully complement. 

See you there
Jad

**Comment by Kira-Cesonia** [comment]
Thanks for the suggestion. I have done as you asked and now posted the issue again here:
https://forum.open-services.net/t/attribute-value-uri-cant-be-resolved/406 

From my perspective, this still qualifies as an issue, though I'm not sure if it is because of LYO or some of the other components involved.

All I know is that using the LYO function `oslcOauthClient.getResource()` I get (among other things) above mentioned URI, and to me it feels like I should be able to call `oslcOauthClient.getResource()` with that URI again to get the attribute value it stands for. That is my personal user story associated with this issue.

**Comment by jadelkhoury** [comment]
Hi

Closing this issue. sent a reply to the forum! I am happy to open the issue again, if we decide it is indeed an Lyo bug/feature. My guess at the moment is that it is not.
